version: '3.8'
services:
  notification-service:
    image: melowetty/notification-service
    volumes:
      - ./build:/home/gradle/project/build
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - KAFKA_BOOTSTRAP_SERVERS=$KAFKA_SERVERS
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://$SERVICE_DISCOVERY_USER:$SERVICE_DISCOVERY_PASSWORD@$SERVICE_DISCOVERY_HOST:$SERVICE_DISCOVERY_PORT/eureka
    restart: always
    networks:
      - service-discovery_internal
      - message-broker_shared
networks:
  service-discovery_internal:
    external: true
  message-broker_shared:
    external: true
