name: Tests and build

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: chmod +x gradlew ; CI=true ./gradlew clean spotlessApply build
      - name: Test
        run: ./gradlew check
        
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-gradle-output
          path: |
            build/libs/notification-service-standalone.jar
          retention-days: 1
